#!/bin/sh

# Terminate on first failure
set -e

errors=0

# Delete existing branches
git checkout --detach
for branch in $(git for-each-ref --format '%(refname:short)' refs/heads); do
  git branch -D $branch
done

# Add and fetch remotes
git remote add from $1  2>/dev/null || git remote set-url from $1
git fetch --multiple --prune from origin

# Create locals
for pushfrom in $(git for-each-ref --format '%(refname)' refs/remotes/from); do
  name="${pushfrom##refs/remotes/from/}"
  pushto="refs/remotes/origin/$name"
  if ( ! git show-ref $pushto > /dev/null) || git merge-base --is-ancestor $pushto $pushfrom > /dev/null; then
    git branch -f $name $pushfrom
  else
    echo "Failed to fast-forward $pushfrom to $pushto, relevant commits:"
    git show-ref $name
    errors=1
  fi
done

# Push to remotes
git push --tags --follow-tags origin refs/heads/*:refs/heads/*

exit $errors
